### ISSUE TITLE
Monotone can be strictly increasing or strictly decreasing

### ISSUE THREAD

**Issue by innovimax** [stepchowfun/coq-fun#9]
https://github.com/stepchowfun/coq-fun/blob/fc90af9f7a122afd74241ed8414f81926a3b3b00/coq/Kleene.v#L74

https://en.wikipedia.org/wiki/Monotonic_function

**Comment by stepchowfun** [comment]
What is the issue? There are a few different flavors of monotone functions. This one is not strict (because partial orders are reflexive), so it doesn't match the title of the issue.

**Comment by stepchowfun** [comment]
This is the standard definition for monotone in domain theory (the one that is implied by Scott continuity), so I will close this. But maybe I am missing something, so feel free to re-open if that is the case.

**Comment by innovimax** [comment]
I removed strict which wasn't true. and thanks for the detailed answer. Domain theory looks even more interesting now !

**Comment by stepchowfun** [comment]
You will find that this definition of `monotone`/`monotonic` is pretty common. For example:

<img width="612" alt="screenshot 2017-11-29 08 37 59" src="https://user-images.githubusercontent.com/796574/33386802-a39fc620-d4e0-11e7-9050-7bbe7ef32cba.png">

That was taken from [this domain theory book](https://www.scss.tcd.ie/Andrew.Butterfield/Teaching/CS4003/DenSem-full-book.pdf). Every other domain theory resource I've come across uses this definition.

**Comment by innovimax** [comment]
But am I correct that in the sample you provide, we could use different definition for ⊑<sub>A</sub> and ⊑<sub>B</sub>, hence in this case we could say ⊑<sub>A</sub> ≝ \leq and ⊑<sub>B</sub> ≝ \geq and hence it covers increasing and decreasing monotonic ?

**Comment by stepchowfun** [comment]
> we could say ⊑<sub>A</sub> ≝ \leq and ⊑<sub>B</sub> ≝ \geq and hence it covers increasing and decreasing monotonic

You are asking whether we can define monotone as: `x <= y implies f(x) >= f(y)`?

No, because:

1. We have not defined what `x >= y` means. For partial orders, this is not generally taken to mean `y <= x AND y != x`. To see why, think about the subset relations ⊆ and ⊇ as a partial order.
2. Instead, you could try defining monotone as `x <= y implies f(y) <= f(x)`. But this has the same problem that I mentioned before: it is not implied by Scott-continuity.

Also, that would not be very useful; think about what a monotonically decreasing function would mean in terms of the information order. It makes no sense for computable functions, which are the kind studied in domain theory.

**Comment by innovimax** [comment]
> Also, that would not be very useful; think about what a monotonically decreasing function would mean in terms of the information order. It makes no sense for computable functions, which are the kind studied in domain theory.

Very good point !!!
